### ISSUE TITLE
The difference between FC and SCOUTER?

### ISSUE THREAD

**Issue by chenshen03** [wbw520/scouter#4]
Given a feature map F, the traditional FC layer first average pooling F and then reduce it to the number of class, while SCOUTER first reduces by Conv & ReLU and then sum pooling. The essential transformations are similar, except that SCOUTER has additional attention like No-local. Therefore, can the same explainable results be obtained using only simple Conv & ReLU without attention?

**Comment by conscienceli** [comment]
Thanks for the question. Please see the below image for the answer.

<img width="310" alt="Snipaste_2021-08-06_12-17-05" src="https://user-images.githubusercontent.com/4034943/128455276-9c039482-874f-4e39-9a51-793508b2f0d0.png">

**Comment by chenshen03** [comment]
Thank your very much for your answer.
